import torch
import numpy as np
import h5py
import matplotlib.pyplot as plt


def load_h5(h5_path, dtype=torch.float32, dataset = "heat2d"):
    """
    Load the Navier–Stokes dataset generated by generate_navier_stokes_autoreg().

    Returns:
        omega_in  : torch.Tensor [num_samples, 1, N, N]
        omega_out : torch.Tensor [num_samples, 1, N, N]
    """
    with h5py.File(h5_path, "r") as f:
        if dataset == "heat2d":
            omega = f["u"][:]  # (num_samples, T, N, N)
        elif dataset == "navier_stokes":
            omega = f["omega"][:]
        else:
            raise("Error: passed data string does not correspond to existing dataset. pass 'heat2d' or 'navier_stokes'.")
    
    # Use first and last frame as input/output
    omega_in  = torch.tensor(omega[:, 0, :, :], dtype=dtype)[:, None, :, :]  # (B,1,H,W)
    omega_out = torch.tensor(omega[:, -1, :, :], dtype=dtype)[:, None, :, :] # (B,1,H,W)
    return omega_in, omega_out

def anti_alias_lowpass(x, factor):
    """
    Low-pass x (B,1,H,W) so it can be safely decimated by 'factor'.
    Keeps only frequencies <= new Nyquist after decimation.
    """
    H = x.shape[-2]
    # after decimation by s, new Nyquist index is H/(2*factor)
    cutoff = max(1, H // (2*factor))
    return lowpass(x, modes=cutoff)

def subsample_aa(x, y, factor):
    """Anti-aliased subsample by integer factor in both dims."""
    if factor == 1:
        return x, y
    x_f = anti_alias_lowpass(x, factor)
    y_f = anti_alias_lowpass(y, factor)
    return x_f[:, :, ::factor, ::factor], y_f[:, :, ::factor, ::factor]


def relative_l2(pred, truth):
    """Compute relative L² norm between two tensors of shape (B,1,H,W)."""
    diff = pred - truth
    diff_l2 = torch.sqrt(torch.mean(diff**2, dim=[1,2,3]))
    truth_l2 = torch.sqrt(torch.mean(truth**2, dim=[1,2,3]))
    rel = (diff_l2 / truth_l2).mean().item()
    return rel


def evaluate_subsampled(model, x_full, y_full, factor, train_N=64, modes=16, batch_size=4):
    # 1) anti-aliased subsample to N = 128/factor
    x, y = subsample_aa(x_full, y_full, factor)
    N_eff = x.shape[-1]

    # 2) if testing above training resolution, low-pass BOTH input & target to training band
    if N_eff > train_N:
        x = lowpass(x, modes=modes)
        y = lowpass(y, modes=modes)

    loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(x, y),
                                         batch_size=batch_size, shuffle=False)

    losses = []
    with torch.no_grad():
        for xb, yb in loader:
            xb, yb = xb.cuda(), yb.cuda()
            out = model(xb.permute(0, 2, 3, 1)).permute(0, 3, 1, 2)
            # relative L2 on the same band
            losses.append(relative_l2(out, yb))
    return float(np.mean(losses)), float(np.std(losses)), N_eff



def lowpass(x, modes=16):
    """
    Low-pass filter a 2D tensor to the lowest `modes` Fourier modes.
    x: (B,1,H,W) real tensor
    """
    x_ft = torch.fft.rfft2(x)
    B, C, H, W_half = x_ft.shape
    out_ft = torch.zeros_like(x_ft)
    # keep the lowest `modes` in each dimension
    out_ft[:, :, :modes, :modes] = x_ft[:, :, :modes, :modes]
    out_ft[:, :, -modes:, :modes] = x_ft[:, :, -modes:, :modes]
    x_filtered = torch.fft.irfft2(out_ft, s=(H, 2 * (W_half - 1)))
    return x_filtered

def rfft2_lowpass(x, modes):
    """
    Low-pass filter (B,1,H,W) to the lowest `modes` Fourier indices in each dim.
    """
    x_ft = torch.fft.rfft2(x)                       # (B,1,H,W//2+1), complex
    B, C, H, W2 = x_ft.shape
    keep = min(modes, H//2)                         # safety
    out = torch.zeros_like(x_ft)
    # keep corners for ±kx (first and last H slabs), and ky in [0, keep)
    out[:, :, :keep, :keep] = x_ft[:, :, :keep, :keep]
    out[:, :, -keep:, :keep] = x_ft[:, :, -keep:, :keep]
    x_lp = torch.fft.irfft2(out, s=(H, 2*(W2-1)))
    return x_lp

def anti_alias_and_decimate(x, factor):
    """
    Anti-aliased decimation of (B,1,H,W) by integer factor in both dims.
    """
    if factor == 1:
        return x
    H = x.shape[-2]
    cutoff = max(1, H // (2*factor))               # new Nyquist after decimation
    x_f = rfft2_lowpass(x, modes=cutoff)
    return x_f[:, :, ::factor, ::factor]

def load_heat_h5(h5_path, dtype=torch.float32, device="cuda:0", dataset = "heat2d"):
    """
    Loads heat dataset with key 'u': (num_samples, T, N, N).
    Returns (u0, uT) as (B,1,N,N) tensors on device.
    """
    with h5py.File(h5_path, "r") as f:
        if dataset == "heat2d":
            u = f["u"][:]
        elif dataset == "navier_stokes":
            u = f["omega"][:]
        else:
            raise("Error: passed data string does not correspond to existing dataset. pass 'heat2d' or 'navier_stokes'.")
    
    u0 = torch.tensor(u[:, 0, :, :], dtype=dtype)[:, None, :, :]
    uT = torch.tensor(u[:, -1, :, :], dtype=dtype)[:, None, :, :]
    return u0.to(device), uT.to(device)

def predict(model, u0):
    """
    Runs FNO2D which expects input as (B,H,W,1); returns (B,1,H,W).
    """
    with torch.no_grad():
        out = model(u0.permute(0, 2, 3, 1))
        out = out.permute(0, 3, 1, 2)
    return out

# ---------- main: one sample, multiple subs ----------
def eval_and_plot_sample(h5_path, model, sample_idx=0, subs=(4,2,1),
                         train_N=64, train_modes=16, device="cuda:0",
                         match_band_on_fine=True, dataset = "heat2d"):
    """
    subs: 4->32x32, 2->64x64, 1->128x128 (for N=128 base)
    match_band_on_fine: if True, for sub=1 (128x128) low-pass BOTH input & target to training band
                        before running the model (to avoid distribution shift).
    """
    u0_full, uT_full = load_heat_h5(h5_path, device=device, dataset = dataset)

    # Select sample
    u0_full = u0_full[sample_idx:sample_idx+1]  # (1,1,128,128)
    uT_full = uT_full[sample_idx:sample_idx+1]

    for sub in subs:
        factor = sub                                # here sub is 1/2/4
        N_eff = 128 // factor

        # Build resolution-consistent (anti-aliased) inputs
        u0 = anti_alias_and_decimate(u0_full, factor)   # (1,1,N_eff,N_eff)
        uT = anti_alias_and_decimate(uT_full, factor)

        # OPTIONAL: when testing above training resolution (N_eff > train_N),
        # low-pass BOTH input and target to the training spectral band
        if match_band_on_fine and N_eff > train_N:
            u0 = rfft2_lowpass(u0, modes=train_modes)
            uT = rfft2_lowpass(uT, modes=train_modes)

        # Run model
        pred = predict(model, u0)                       # (1,1,N_eff,N_eff)

        # Move to CPU numpy for plotting
        u0_np = u0[0,0].detach().cpu().numpy()
        uT_np = uT[0,0].detach().cpu().numpy()
        pr_np = pred[0,0].detach().cpu().numpy()
        diff  = uT_np - pr_np

        # ----------------- plots -----------------
        # Main three fields on one row (shared min/max)
        vmin = min(np.min(u0_np), np.min(uT_np), np.min(pr_np))
        vmax = max(np.max(u0_np), np.max(uT_np), np.max(pr_np))

        fig, axes = plt.subplots(1, 3, figsize=(12, 3.7))
        for ax, arr, ttl in zip(
            axes,
            [u0_np, uT_np, pr_np],
            [f"u₀ (N={N_eff})", f"u_T (N={N_eff})", f"pred (N={N_eff})"]):
            im = ax.imshow(arr, cmap="coolwarm", origin="lower", vmin=vmin, vmax=vmax)
            ax.set_title(ttl); ax.axis("off")
        fig.colorbar(im, ax=axes, fraction=0.025, pad=0.04)
        plt.suptitle(f"2D Heat | sample {sample_idx} | sub={sub} (N={N_eff})")
        plt.show()

        # Difference plot on its own scale
        m = np.max(np.abs(diff)) + 1e-12
        plt.figure(figsize=(4.2, 3.7))
        plt.imshow(diff, cmap="bwr", origin="lower", vmin=-m, vmax=+m)
        plt.colorbar(fraction=0.046, pad=0.04, label="u_T − pred")
        plt.title(f"Difference (N={N_eff}) | range ±{m:.2e}")
        plt.axis("off"); plt.show()